[book]
authors = ["Michael Crawford", "Jonee Ryan Ty", "Andrew Price"]
language = "en"
multilingual = false
src = "book"
title = "go-msx"

[build]
build-dir = "docs"
create-missing = false

[output.html]
preferred-dark-theme = "coal"
additional-js = ["book/mermaid.min.js", "book/mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
