executable:
  cmd: app
  configFiles:
    - bootstrap.yml
    - application.properties

msx:
  release: 3.8.0
  platform:
    parentArtifacts:
      - com.cisco.vms:vms-service-starter
      - com.cisco.vms:vms-service-starter-core
      - com.cisco.vms:vms-service-starter-kafka
      - com.cisco.nfv:nfv-integration-consul-leader
    version: 3.8.0-EDGE
    includeGroups: "com.cisco.**"

docker:
  archetype: microservice
