info.build.version: "3.7.0-SNAPSHOT"
info.build.buildNumber: "1000"
info.build.buildDateTime: "2019-11-01T00:00:00.000000Z"
info.build.artifact: "someservice"
info.build.name: "Some Microservice"
info.build.group: "com.cisco.msx.someservice"
