openapi: 3.0.0
info:
  title: KAKAPO - Common Domain
  description: Common components for MSX Platform APIs
  version: '8'

components:
  parameters:
    page:
      in: query
      name: page
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
        example: "0"

    pageSize:
      in: query
      name: pageSize
      required: true
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 1000
        example: "10"

    sortBy:
      in: query
      name: sortBy
      schema:
        type: string
        example: "name"

    sortOrder:
      in: query
      name: sortOrder
      schema:
        type: string
        enum:
          - asc
          - desc

  responses:
    "204":
      description: No Content

    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    "401":
      description: Unauthenticated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    "403":
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    "409":
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    "412":
      description: Precondition Failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    "422":
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    "500":
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          readOnly: true
        message:
          type: string
          readOnly: true

    NameValue:
      type: object
      properties:
        name:
          type: string
        value:
          type: string

    StringArray:
      type: array
      items:
        type: string

    UuidArray:
      type: array
      items:
        type: string
        format: uuid

    PageHeader:
      type: object
      properties:
        page:
          type: integer
          format: int32
          readOnly: true
          example: "0"
        pageSize:
          type: integer
          format: int32
          readOnly: true
          example: "1"
        totalItems:
          type: integer
          format: int64
          readOnly: true
          example: "10"
        hasNext:
          type: boolean
          readOnly: true
          nullable: true
          example: "false"
        hasPrevious:
          type: boolean
          readOnly: true
          nullable: true
          example: "false"
        sortBy:
          type: string
          readOnly: true
          example: "name"
        sortOrder:
          type: string
          enum:
            - asc
            - desc
          readOnly: true
          example: "asc"

    Name:
      type: string
      minLength: 1
      maxLength: 128

    Label:
      type: string
      minLength: 1
      maxLength: 128

    Description:
      type: string
      minLength: 1
      maxLength: 512
