name: Index
on: push
env:
  CHECKS_ENTERPRISE_TOKEN: ${{ secrets.ENTERPRISE_TOKEN }}
  CHECKS_ENTERPRISE_KEY: ${{ secrets.ENTERPRISE_KEY }}
  CHECKS_PUBLIC_TOKEN: ${{ secrets.PUBLIC_TOKEN }}
  GOPRIVATE: cto-github.cisco.com/NFV-BU,github.com/cpx-saas
  GOPROXY: proxy.golang.org,direct
jobs:
  Index:
    if: github.repository == 'cpx-saas/go-msx'
    runs-on: [ self-hosted, Linux ]
    container: dockerhub.cisco.com/docker.io/sourcegraph/lsif-go:latest
    env:
      SRC_ENDPOINT: https://sg.infra.ciscomsx.com
      SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN }}
      INDEX_REPO: cto-github.cisco.com/NFV-BU/go-msx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure git
        uses: cpx-saas/actions-msx-checks@master
        with:
          check: git-config
      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Generate index
        run: lsif-go --no-animation
          --repository-remote="$INDEX_REPO"
      - name: Upload index
        run: src lsif upload
          -github-token=${{ secrets.ENTERPRISE_TOKEN }}
          -ignore-upload-failure
          -no-progress
          -repo $INDEX_REPO
